version: "3.9"

services:
  imggen:
    build: ./
    ports:
      - "8069:8000"
    volumes:
      - out:/images
      - cache:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
volumes:
  out:
  cache:
